export { default as AuthPage } from './AuthPage';
export {default as DocumentsPage} from './DocumentsPage';
export {default as AnnouncementsPage} from './AnnouncementsPage';
export {default as UsersPage} from './UsersPage';
export {default as IssuesPage} from './IssuesPage';
export {default as UserDetailsPage} from './UserDetailsPage';
export {default as ProfilePage} from './ProfilePage';
export {default as BuildingsPage} from './BuildingsPage';
export {default as BuildingDetailsPage} from './BuildingDetailsPage';
export {default as LocalsPage} from './LocalsPage';
